command:
  - streamlit
  - run
  - app.py

env:
  - name: NEO4J_URI
    valueFrom: neo4j_uri

  - name: NEO4J_USERNAME
    valueFrom: neo4j_username

  - name: NEO4J_PASSWORD
    valueFrom: neo4j_password

  - name: ANALYSIS_JOB_ID
    valueFrom: analysis_job

  - name: CLASS_D_ANALYSIS_JOB_ID
    valueFrom: class_d_analysis_job

  - name: CLASS_D_GPT20_ENDPOINT
    valueFrom: class_d_gpt20_endpoint

  - name: CLASS_D_OLLAMA_LLAMA70_URL
    valueFrom: class_d_ollama_llama70_url

  - name: DIRECT_TEXT_ENCRYPTION_KEY
    valueFrom: direct_text_encryption_key

  - name: IKG_ADMIN_USERS
    valueFrom: ikg_admin_users

  - name: LLAMA_DAILY_QUESTION_LIMIT
    value: "5"

  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
